### ISSUE TITLE
مشکل در فرمت تبدیل تاریخ

### ISSUE THREAD

**Issue by kiaxseventh** [mehdi-nemati/persian_number_utility#12]
سلام و خسته نباشید
در بخش توضیحات نحوه استفاده ، مورد زیر ذکر شده است
```
    //تبدیل تاریخ میلادی به تاریخ شمسی
        Text(DateTime.now().toPersianDate()),//۱۳۹۹/۰۷/۱۶
```
در صورتی که متد
 toPersianData
  به جای
 ۱۳۹۹/۰۷/۰۶
   مقدار ۱۳۹۹/۷/۶  باز میگرداند 

با تشکر بابت این پکیج بسیار کاربردی

**Comment by mehdi-nemati** [comment]
سلام وقتتون بخیر
نسخه جدید منتشر شده ، و این امکان اضافه شده بهش
DateTime.now().toPersianDate(twoDigits: true)
