### ISSUE TITLE
مشکل در تبدیل تاریخ

### ISSUE THREAD

**Issue by MansoorJafari9** [mehdi-nemati/persian_number_utility#15]
سلام
تاریخ رو یک روز قبل میزنه
مثلا امروز 1400/4/3 هست
تاریخ رو تبدیل میکنه 1400/4/2

**Comment by mehdi-nemati** [comment]
سلام ، تست شد مشکلی وجود نداشت ، دقت کنین که اگه از نسخه های قدیمی تر استفاده میکنین، از آخرین نسخه استفاده کنین

![image](https://user-images.githubusercontent.com/40987090/123219336-06feee80-d4e2-11eb-9dae-c0819a2c41e6.png)
