### ISSUE TITLE
تبدیل ي به ی و ك به ک

### ISSUE THREAD

**Issue by AliEasy** [mehdi-nemati/persian_number_utility#21]
سلام
توی (بعضی) کیبورد های ios این مشکل به وجود میاد که به جای ی، ي وارد میشه اگه بشه replace کردشون عالی میشه
مرسی

**Comment by mehdi-nemati** [comment]
سلام، این موردی که خواستین اضافه شده به شکل زیر میتونین استفاده کنید

'your string'.fixPersianChars()

کاراکتر های  ک ی ه  رو پوشش میده

موفق باشی دوست عزیز ✌
