### ISSUE TITLE
Please support Null safety

### ISSUE THREAD

**Issue by MahdiPixel** [mehdi-nemati/persian_number_utility#22]
نال سیفتی رو ساپورت نمی کنه ، نتونستم تو فلاتر 3.0.1 اضافه ش کنم

**Comment by mehdi-nemati** [comment]
سلام، نال سیفتی پشتیبانی میشه و تو سایت pub.dev هم مشخصه و در حال حاضر هم خودم تو فلاتر 3.0.4 دارم استفاده میکنم و مشکلی نداره، اگه از نسخه قدیمی پکیج استفاده میکتین ، به آخرین نسخه آپدیت کنین

![image](https://user-images.githubusercontent.com/40987090/179900459-c4d3aeb2-a22a-4cc4-97d8-561305d337f6.png)
