### ISSUE TITLE
نیاز به ساعت علاوه بر تاریخ

### ISSUE THREAD

**Issue by mahdiqdi** [mehdi-nemati/persian_number_utility#23]
سلام امیدوارم حالتون خوب باشه.ممنون از پکیج خوبتون ولی من یک مشکلی دارم.من میخوام از toPersianDate استفاده کنم ولی زمان رو هم احتیاج دارم.چون علاوه بر تاریخ زمان هم برام مهمه.حالا میشه راهنماییم کنید چیکارش میتونم بکنم؟باید از پکیچ  دیگه ای استفاده کنم؟

**Comment by mehdi-nemati** [comment]
سلام دوست عزیز، ممنونم از لطف شما،   از نسخه **1.1.3** استفاده کنید، طریقه استفاده هم به صورت زیر 
`.toPersianDate(showTime: true,timeSeprator: ' - ')`
مقدار `showTime` رو `true` کنید
مقدار `timeSeprator` کاراکتر جداکننده ای هست که بین تاریخ و زمان قرار میگیره که با توجه به نیازتون تغییر بدین
همچنین اگه نیاز بود که زمان در سمت راست یا چپ متن قرار بگیرد مقدار `changeDirectionShowTimw` رو تغییر بدین

مثال کامل هم به این صورت هست :
`DateTime.now().toPersianDate(
                    showTime: true,
                    changeDirectionShowTimw: false,
                    showTimeSecond: true,
                    timeSeprator: ' - ',digitType:NumStrLanguage.Farsi,
                    twoDigits: true)`

موفق باشید ✌

**Comment by mahdiqdi** [comment]
ممنونم ازتون که اینقدر سریع توجه کردید.خیلی خیلی لطف کردید.چک میکنم بهتون خبر میدم

**Comment by mahdiqdi** [comment]
عالی شد جناب نعمتی.دستتون درد نکنه
