### ISSUE TITLE
تشخیص صحیح بودن کد پستی

### ISSUE THREAD

**Issue by farhadrezvani7** [mehdi-nemati/persian_number_utility#30]
درود بر شما
اگر این امکان رو هم به پکیج اضافه کنید، عالی میشه.
با تشکر

**Comment by mehdi-nemati** [comment]
سلام؛ تو نسخه 1.1.4 این مورد اضافه شده
متد: isValidIranianPostalCode

**Comment by farhadrezvani7** [comment]
سلام با تشکر
