### ISSUE TITLE
قابلیت مرتب کردن اعداد به صورت قیمت

### ISSUE THREAD

**Issue by hashemim66110** [mehdi-nemati/persian_number_utility#34]
سلام
یه قابلیت که راحت میشه پیادش کرد و خیلی به کار میاد
اینه که اعداد رو مثل
۱۲۳۴۵۶
به
۱۲۳٫۴۵۶
تبدیل کنه.
هر ۳ رقم بینشون یه ٫ بذاره.

ممنون میشم اضافه کنید :)

**Comment by mehdi-nemati** [comment]
سلام؛ این متد وجود داره میتونین از این روش استفاده کنین
`Text("100092".seRagham()),//100,092`
یا
`Text("100092".seRagham(separator: "-")),//100-092`
