### ISSUE TITLE
extractNumber issue

### ISSUE THREAD

**Issue by deep01code** [mehdi-nemati/persian_number_utility#4]
parsian_number_urility.dart

line 50

`var arabicNumbers = ['٩', '٨', '٧', '٦', '٥', '٤', '٣', '٢', '١', '٠'];`

reverse the order of this array, it gives wrong values when called for Arabic values.

example 

flutter: ٥٦٠٨٧٧٧٨٨
flutter: 439122211

**Comment by mehdi-nemati** [comment]
This issue fixed .please install last version.
