### ISSUE TITLE
The order of Arabic numbers is reversed

### ISSUE THREAD

**Issue by black-8** [mehdi-nemati/persian_number_utility#5]
for example:
`changeDigit('١٢٣٤',NumStrLanguage.English)`
will result in => 8765

As far as I find out it's an RTL/IDE related  problem

I'm testing on iPhone 5s and Arabic keyboard
 
it should pass this test:
`
test('convert Farsi/Arabic digits to English ascii Characters', () {
    expect(
        NumberUtility.changeDigit('۱۲۳۴۵۶۷۸۹۰', NumStrLanguage.English),
        '1234567890');
    expect(
        NumberUtility.changeDigit('١٢٣٤٥٦٧٨٩٠', NumStrLanguage.English),
        '1234567890');
  });
`

current result
`package:test_api                                   expect
package:flutter_test/src/widget_tester.dart 369:3  expect
test/persian_number_utility_test.dart 11:5         main.<fn>

Expected: '1234567890'
  Actual: '8765432109'
   Which: is different.
          Expected: 1234567890 ...
            Actual: 8765432109 ...
                    ^
           Differ at offset 0`

**Comment by mehdi-nemati** [comment]
The package was tested according to your problems and with the sample code you sent, which showed no problem and the output is exactly according to the expected answer.

Be sure to use the **latest version** of the package (currently version 0.2.2)

The test image of the package is attached below.
![image](https://user-images.githubusercontent.com/40987090/95739660-07c75b80-0c98-11eb-828c-dac30fb315de.png)
